/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type WorldId = string;
export type ValueJs = string;
export type Key = string | null;
export type Index = number | null;
export type EntityId = string | null;
export type PathElements = GeneratablePathElement[];
export type GenerationId = string;
export type GenerationId1 = string;
export type GenerationId2 = string;
export type GenerationId3 = string;
export type WorldId1 = string;
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "EntityType".
 */
export type EntityType =
  | "world"
  | "character"
  | "item"
  | "resource"
  | "region"
  | "plot_stage"
  | "dialogue"
  | "tool"
  | "vehicle"
  | "building"
  | "crafting_option"
  | "crafting_location"
  | "animal";
export type Name = string | null;
export type EntityId1 = string;
/**
 * Name of the world
 */
export type Name1 = string;
export type WorldId2 = string;
export type EntityId2 = string;
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationEndpoint".
 */
export type GenerationEndpoint = "character" | "characters";
export type EntityToGenerate = string | null;
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratorType".
 */
export type GeneratorType = "ollama" | "openai" | "hugging_face";
export type GModelId = string;
export type GenerationId4 = string;
export type EntityId3 = string;
export type Name2 = string | null;
export type ImageUri = string | null;
export type CreatedAt = string;
export type UpdatedAt = string;
export type Js = string;
export type RawValue = string;
export type ValueJs1 = string;
export type DisplayPath = string[];
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratedValueType".
 */
export type GeneratedValueType =
  | "generated_string"
  | "generated_float"
  | "generated_int"
  | "generated_boolean"
  | "generated_object"
  | "generated_list";
export type Choices = string[] | null;
export type ValidationErrors = string[];
export type Fields = GeneratedItem[];
export type EntityId4 = string;
export type Name3 = string | null;
export type ImageUri1 = string | null;
export type CreatedAt1 = string;
export type UpdatedAt1 = string;
export type GenerationId5 = string;
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationType".
 */
export type GenerationType = "text" | "image" | "audio";
export type BeginTime = string;
export type EndTime = string | null;
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationStatus".
 */
export type GenerationStatus = "queued" | "in_progress" | "streaming" | "error" | "complete";
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "MessageSourceRole".
 */
export type MessageSourceRole = "system" | "user" | "assistant";
export type Message = string;
export type PromptMessages = GenerationMessage[];
export type JsonSchema = string | null;
export type MaxTokens = number | null;
export type Temperature = number | null;
export type TopP = number | null;
export type FrequencyPenalty = number | null;
export type PresencePenalty = number | null;
export type InputTokens = number | null;
export type OutputTokens = number | null;
export type GenerationId6 = string;
export type BeginTime1 = string;
export type EndTime1 = string | null;
export type WorldId3 = string;
export type EntityId5 = string | null;
export type WorldId4 = string;
export type Entities = GeneratedEntityListItem[];
export type Generations = GenerationListItem[];
export type ModelName = string;
export type LoadedModels = LoadedModel[];
export type ModelName1 = string;
export type LoadedModelId = string;
export type WorldId5 = string;
export type WorldId6 = string;
export type NewValueJs = string;
export type LoadedModelId1 = string;

export interface CairneSchema {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "AppendElementRequest".
 */
export interface AppendElementRequest {
  world_id: WorldId;
  value_js: ValueJs;
  path: GeneratablePath;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratablePath".
 */
export interface GeneratablePath {
  path_elements?: PathElements;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratablePathElement".
 */
export interface GeneratablePathElement {
  key?: Key;
  index?: Index;
  entity_id?: EntityId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "AppendElementResponse".
 */
export interface AppendElementResponse {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ApplyGenerationRequest".
 */
export interface ApplyGenerationRequest {
  generation_id: GenerationId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ApplyGenerationResponse".
 */
export interface ApplyGenerationResponse {
  generation_id: GenerationId1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "CancelGenerationRequest".
 */
export interface CancelGenerationRequest {
  generation_id: GenerationId2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "CancelGenerationResponse".
 */
export interface CancelGenerationResponse {
  generation_id: GenerationId3;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "CreateEntityRequest".
 */
export interface CreateEntityRequest {
  world_id: WorldId1;
  entity_type: EntityType;
  name: Name;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "CreateEntityResponse".
 */
export interface CreateEntityResponse {
  entity_id: EntityId1;
  path: GeneratablePath;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "CreateWorldRequest".
 */
export interface CreateWorldRequest {
  name: Name1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "DeleteEntityRequest".
 */
export interface DeleteEntityRequest {
  world_id: WorldId2;
  entity_id: EntityId2;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "DeleteEntityResponse".
 */
export interface DeleteEntityResponse {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerateRequest".
 */
export interface GenerateRequest {
  generation_endpoint: GenerationEndpoint;
  entity_to_generate?: EntityToGenerate;
  generator_model?: GeneratorModel;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratorModel".
 */
export interface GeneratorModel {
  generator_type: GeneratorType;
  g_model_id: GModelId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerateResponse".
 */
export interface GenerateResponse {
  generation_id: GenerationId4;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratedEntity".
 */
export interface GeneratedEntity {
  entity_id: EntityId3;
  name: Name2;
  image_uri: ImageUri;
  created_at: CreatedAt;
  updated_at: UpdatedAt;
  path: GeneratablePath;
  js?: Js;
  fields: Fields;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratedItem".
 */
export interface GeneratedItem {
  raw_value: RawValue;
  value_js: ValueJs1;
  display_path?: DisplayPath;
  value_type: GeneratedValueType;
  edit_path: GeneratablePath;
  choices?: Choices;
  validation_errors?: ValidationErrors;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GeneratedEntityListItem".
 */
export interface GeneratedEntityListItem {
  entity_id: EntityId4;
  name: Name3;
  image_uri: ImageUri1;
  created_at: CreatedAt1;
  updated_at: UpdatedAt1;
  path: GeneratablePath;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "Generation".
 */
export interface Generation {
  generation_id?: GenerationId5;
  endpoint: GenerationEndpoint;
  generation_type: GenerationType;
  generator_model: GeneratorModel;
  begin_time?: BeginTime;
  end_time?: EndTime;
  status?: GenerationStatus & string;
  prompt_messages?: PromptMessages;
  json_schema?: JsonSchema;
  parameters?: GenerationRequestParameters;
  input_tokens?: InputTokens;
  output_tokens?: OutputTokens;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationMessage".
 */
export interface GenerationMessage {
  source: MessageSourceRole;
  message: Message;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationRequestParameters".
 */
export interface GenerationRequestParameters {
  max_tokens?: MaxTokens;
  temperature?: Temperature;
  top_p?: TopP;
  frequency_penalty?: FrequencyPenalty;
  presence_penalty?: PresencePenalty;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationHistory".
 */
export interface GenerationHistory {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationListItem".
 */
export interface GenerationListItem {
  generation_id: GenerationId6;
  begin_time: BeginTime1;
  end_time: EndTime1;
  status: GenerationStatus;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GenerationState".
 */
export interface GenerationState {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GetEntityRequest".
 */
export interface GetEntityRequest {
  world_id: WorldId3;
  entity_id?: EntityId5;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GetEntityResponse".
 */
export interface GetEntityResponse {
  entity: GeneratedEntity;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "GetGenerationResponse".
 */
export interface GetGenerationResponse {
  generation: Generation;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ListEntitiesRequest".
 */
export interface ListEntitiesRequest {
  world_id: WorldId4;
  entity_type: EntityType;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ListEntitiesResponse".
 */
export interface ListEntitiesResponse {
  entities?: Entities;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ListGenerationsResponse".
 */
export interface ListGenerationsResponse {
  generations?: Generations;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ListLoadedModelsRequest".
 */
export interface ListLoadedModelsRequest {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ListLoadedModelsResponse".
 */
export interface ListLoadedModelsResponse {
  loaded_models: LoadedModels;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "LoadedModel".
 */
export interface LoadedModel {
  model_name: ModelName;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "LoadModelRequest".
 */
export interface LoadModelRequest {
  model_name: ModelName1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "LoadModelResponse".
 */
export interface LoadModelResponse {
  loaded_model_id: LoadedModelId;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "RemoveValueRequest".
 */
export interface RemoveValueRequest {
  world_id: WorldId5;
  path: GeneratablePath;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "RemoveValueResponse".
 */
export interface RemoveValueResponse {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ReplaceRequest".
 */
export interface ReplaceRequest {
  world_id: WorldId6;
  new_value_js: NewValueJs;
  path: GeneratablePath;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "ReplaceResponse".
 */
export interface ReplaceResponse {
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "UnloadModelRequest".
 */
export interface UnloadModelRequest {
  loaded_model_id: LoadedModelId1;
  [k: string]: unknown;
}
/**
 * This interface was referenced by `CairneSchema`'s JSON-Schema
 * via the `definition` "UnloadModelResponse".
 */
export interface UnloadModelResponse {
  [k: string]: unknown;
}
